project:
  type: website
  output-dir: docs

book:
  title: "CASA0025 Final Assessment"
  author: "Group Name"
  date: "01/01/2024"
  chapters:
    - index.qmd

  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: casa_logo.png



format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
